/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicketJavaGUI;

/**
 *
 * @author DReyes
 */
public class AdministradorEventos extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionEventos
     */
    public AdministradorEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombreCrearUsu1 = new javax.swing.JLabel();
        txt_nombreCrearUsu1 = new javax.swing.JTextField();
        lbl_usuarioCrearUsu1 = new javax.swing.JLabel();
        txt_usuarioCrearUsu1 = new javax.swing.JTextField();
        lbl_contraCrearUsu1 = new javax.swing.JLabel();
        txt_contraCrearUsu1 = new javax.swing.JTextField();
        lbl_edadCrearUsu1 = new javax.swing.JLabel();
        txt_edadCrearUsu1 = new javax.swing.JTextField();
        lbl_tipoCrearUsu1 = new javax.swing.JLabel();
        combo_tipoCrearUsu1 = new javax.swing.JComboBox();
        btn_crearUsuario1 = new javax.swing.JButton();
        lbl_edadCrearUsu2 = new javax.swing.JLabel();
        txt_edadCrearUsu2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_nombreCrearUsu2 = new javax.swing.JLabel();
        txt_nombreCrearUsu2 = new javax.swing.JTextField();
        lbl_usuarioCrearUsu2 = new javax.swing.JLabel();
        txt_usuarioCrearUsu2 = new javax.swing.JTextField();
        lbl_contraCrearUsu2 = new javax.swing.JLabel();
        txt_contraCrearUsu2 = new javax.swing.JTextField();
        lbl_edadCrearUsu3 = new javax.swing.JLabel();
        txt_edadCrearUsu3 = new javax.swing.JTextField();
        lbl_edadCrearUsu4 = new javax.swing.JLabel();
        txt_edadCrearUsu4 = new javax.swing.JTextField();
        lbl_tipoCrearUsu2 = new javax.swing.JLabel();
        combo_tipoCrearUsu2 = new javax.swing.JComboBox();
        btn_crearUsuario2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nombreCrearUsu3 = new javax.swing.JLabel();
        txt_nombreCrearUsu3 = new javax.swing.JTextField();
        btn_crearUsuario3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_nombreCrearUsu4 = new javax.swing.JLabel();
        txt_nombreCrearUsu4 = new javax.swing.JTextField();
        btn_crearUsuario4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nombreCrearUsu1.setText("Codigo");

        txt_nombreCrearUsu1.setToolTipText("Usuario");
        txt_nombreCrearUsu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCrearUsu1ActionPerformed(evt);
            }
        });

        lbl_usuarioCrearUsu1.setText("Titulo");

        txt_usuarioCrearUsu1.setToolTipText("Usuario");

        lbl_contraCrearUsu1.setText("Descripción");

        lbl_edadCrearUsu1.setText("Fecha de Evento");

        txt_edadCrearUsu1.setToolTipText("Usuario");

        lbl_tipoCrearUsu1.setText("Tipo");

        combo_tipoCrearUsu1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativo", "De Contenido", "Limitado" }));
        combo_tipoCrearUsu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoCrearUsu1ActionPerformed(evt);
            }
        });

        btn_crearUsuario1.setText("Crear Evento");
        btn_crearUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuario1ActionPerformed(evt);
            }
        });

        lbl_edadCrearUsu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_edadCrearUsu2.setText("Renta");

        txt_edadCrearUsu2.setToolTipText("Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btn_crearUsuario1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_contraCrearUsu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_contraCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_usuarioCrearUsu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_usuarioCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombreCrearUsu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombreCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_edadCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tipoCrearUsu1)
                                    .addComponent(lbl_edadCrearUsu1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_edadCrearUsu2)
                                    .addComponent(txt_edadCrearUsu1)
                                    .addComponent(combo_tipoCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreCrearUsu1)
                    .addComponent(txt_nombreCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioCrearUsu1)
                    .addComponent(txt_usuarioCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraCrearUsu1)
                    .addComponent(txt_contraCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edadCrearUsu1)
                    .addComponent(txt_edadCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edadCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_edadCrearUsu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_tipoCrearUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoCrearUsu1))
                .addGap(18, 18, 18)
                .addComponent(btn_crearUsuario1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Editar.addTab("Crear", jPanel1);

        lbl_nombreCrearUsu2.setText("Codigo");

        txt_nombreCrearUsu2.setToolTipText("Usuario");
        txt_nombreCrearUsu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCrearUsu2ActionPerformed(evt);
            }
        });

        lbl_usuarioCrearUsu2.setText("Titulo");

        txt_usuarioCrearUsu2.setToolTipText("Usuario");

        lbl_contraCrearUsu2.setText("Descripción");

        lbl_edadCrearUsu3.setText("Fecha de Evento");

        txt_edadCrearUsu3.setToolTipText("Usuario");

        lbl_edadCrearUsu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_edadCrearUsu4.setText("Renta");

        txt_edadCrearUsu4.setToolTipText("Usuario");

        lbl_tipoCrearUsu2.setText("Tipo");

        combo_tipoCrearUsu2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativo", "De Contenido", "Limitado" }));
        combo_tipoCrearUsu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoCrearUsu2ActionPerformed(evt);
            }
        });

        btn_crearUsuario2.setText("Crear Evento");
        btn_crearUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuario2ActionPerformed(evt);
            }
        });

        lbl_nombreCrearUsu3.setText("Codigo");

        txt_nombreCrearUsu3.setToolTipText("Usuario");
        txt_nombreCrearUsu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCrearUsu3ActionPerformed(evt);
            }
        });

        btn_crearUsuario3.setText("Buscar Evento");
        btn_crearUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuario3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_nombreCrearUsu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombreCrearUsu3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_crearUsuario3)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_crearUsuario2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_edadCrearUsu4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tipoCrearUsu2)
                            .addComponent(lbl_edadCrearUsu3)
                            .addComponent(lbl_contraCrearUsu2)
                            .addComponent(lbl_usuarioCrearUsu2)
                            .addComponent(lbl_nombreCrearUsu2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_tipoCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombreCrearUsu2)
                            .addComponent(txt_usuarioCrearUsu2)
                            .addComponent(txt_edadCrearUsu3)
                            .addComponent(txt_contraCrearUsu2)
                            .addComponent(txt_edadCrearUsu4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreCrearUsu3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombreCrearUsu3)
                    .addComponent(btn_crearUsuario3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombreCrearUsu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioCrearUsu2)
                    .addComponent(txt_usuarioCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraCrearUsu2)
                    .addComponent(txt_contraCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edadCrearUsu3)
                    .addComponent(txt_edadCrearUsu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edadCrearUsu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_edadCrearUsu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_tipoCrearUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoCrearUsu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_crearUsuario2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Editar.addTab("Editar", jPanel2);

        lbl_nombreCrearUsu4.setText("Codigo");

        txt_nombreCrearUsu4.setToolTipText("Usuario");
        txt_nombreCrearUsu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCrearUsu4ActionPerformed(evt);
            }
        });

        btn_crearUsuario4.setText("Eliminar Evento");
        btn_crearUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuario4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_crearUsuario4)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_nombreCrearUsu4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombreCrearUsu4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreCrearUsu4)
                    .addComponent(txt_nombreCrearUsu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btn_crearUsuario4)
                .addGap(110, 110, 110))
        );

        Editar.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Editar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreCrearUsu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCrearUsu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCrearUsu1ActionPerformed

    private void combo_tipoCrearUsu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoCrearUsu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipoCrearUsu1ActionPerformed

    private void btn_crearUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearUsuario1ActionPerformed

    private void txt_nombreCrearUsu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCrearUsu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCrearUsu2ActionPerformed

    private void combo_tipoCrearUsu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoCrearUsu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipoCrearUsu2ActionPerformed

    private void btn_crearUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearUsuario2ActionPerformed

    private void txt_nombreCrearUsu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCrearUsu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCrearUsu3ActionPerformed

    private void btn_crearUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearUsuario3ActionPerformed

    private void txt_nombreCrearUsu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCrearUsu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCrearUsu4ActionPerformed

    private void btn_crearUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearUsuario4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Editar;
    private javax.swing.JButton btn_crearUsuario1;
    private javax.swing.JButton btn_crearUsuario2;
    private javax.swing.JButton btn_crearUsuario3;
    private javax.swing.JButton btn_crearUsuario4;
    private javax.swing.JComboBox combo_tipoCrearUsu1;
    private javax.swing.JComboBox combo_tipoCrearUsu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_contraCrearUsu1;
    private javax.swing.JLabel lbl_contraCrearUsu2;
    private javax.swing.JLabel lbl_edadCrearUsu1;
    private javax.swing.JLabel lbl_edadCrearUsu2;
    private javax.swing.JLabel lbl_edadCrearUsu3;
    private javax.swing.JLabel lbl_edadCrearUsu4;
    private javax.swing.JLabel lbl_nombreCrearUsu1;
    private javax.swing.JLabel lbl_nombreCrearUsu2;
    private javax.swing.JLabel lbl_nombreCrearUsu3;
    private javax.swing.JLabel lbl_nombreCrearUsu4;
    private javax.swing.JLabel lbl_tipoCrearUsu1;
    private javax.swing.JLabel lbl_tipoCrearUsu2;
    private javax.swing.JLabel lbl_usuarioCrearUsu1;
    private javax.swing.JLabel lbl_usuarioCrearUsu2;
    private javax.swing.JTextField txt_contraCrearUsu1;
    private javax.swing.JTextField txt_contraCrearUsu2;
    private javax.swing.JTextField txt_edadCrearUsu1;
    private javax.swing.JTextField txt_edadCrearUsu2;
    private javax.swing.JTextField txt_edadCrearUsu3;
    private javax.swing.JTextField txt_edadCrearUsu4;
    private javax.swing.JTextField txt_nombreCrearUsu1;
    private javax.swing.JTextField txt_nombreCrearUsu2;
    private javax.swing.JTextField txt_nombreCrearUsu3;
    private javax.swing.JTextField txt_nombreCrearUsu4;
    private javax.swing.JTextField txt_usuarioCrearUsu1;
    private javax.swing.JTextField txt_usuarioCrearUsu2;
    // End of variables declaration//GEN-END:variables
}
