/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicketJavaGUI;

import TicketJavaGUI.IngresoUsuarios;
import Usuarios.AdmUsuarios;
import Usuarios.Usuario;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author DReyes
 */
public class AdministradorUsuarios extends javax.swing.JFrame {
    
    AdmUsuarios usuarios;
    Usuario usu;
    IngresoUsuarios iu;
    String usuari;
    int tip;
    
    
    public AdministradorUsuarios() {
        usuarios = new AdmUsuarios();
        iu = new IngresoUsuarios(usuarios);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_usuarioCrearUsu = new javax.swing.JLabel();
        lbl_contraCrearUsu = new javax.swing.JLabel();
        txt_usuarioCrearUsu = new javax.swing.JTextField();
        lbl_nombreCrearUsu = new javax.swing.JLabel();
        txt_nombreCrearUsu = new javax.swing.JTextField();
        lbl_edadCrearUsu = new javax.swing.JLabel();
        txt_edadCrearUsu = new javax.swing.JTextField();
        combo_tipoCrearUsu = new javax.swing.JComboBox();
        lbl_tipoCrearUsu = new javax.swing.JLabel();
        btn_crearUsuario = new javax.swing.JButton();
        txt_contraCrearUsu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_nombreEditUsu = new javax.swing.JTextField();
        lbl_nombreEditUsu = new javax.swing.JLabel();
        lbl_usuarioEditUsu = new javax.swing.JLabel();
        txt_usuarioEditUsu = new javax.swing.JTextField();
        lbl_contraEditUsu = new javax.swing.JLabel();
        txt_contraEditUsu = new javax.swing.JTextField();
        lbl_edadEditUsu = new javax.swing.JLabel();
        txt_edadEditUsu = new javax.swing.JTextField();
        lbl_tipoEditUsu = new javax.swing.JLabel();
        btn_editUsuario = new javax.swing.JButton();
        lbl_usuarioBuscUsu = new javax.swing.JLabel();
        txt_usuarioBuscUsu = new javax.swing.JTextField();
        btn_buscUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbl_usuarioElimUsu = new javax.swing.JLabel();
        txt_usuarioElimUsu = new javax.swing.JTextField();
        btn_eliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_usuarioCrearUsu.setText("Usuario");

        lbl_contraCrearUsu.setText("Contraseña");

        txt_usuarioCrearUsu.setToolTipText("Usuario");

        lbl_nombreCrearUsu.setText("Nombre Completo");

        txt_nombreCrearUsu.setToolTipText("Usuario");
        txt_nombreCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCrearUsuActionPerformed(evt);
            }
        });

        lbl_edadCrearUsu.setText("Edad");

        txt_edadCrearUsu.setToolTipText("Usuario");

        combo_tipoCrearUsu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativo", "De Contenido", "Limitado" }));
        combo_tipoCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoCrearUsuActionPerformed(evt);
            }
        });

        lbl_tipoCrearUsu.setText("Tipo");

        btn_crearUsuario.setText("Crear Usuario");
        btn_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btn_crearUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_contraCrearUsu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_contraCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_usuarioCrearUsu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_usuarioCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_tipoCrearUsu)
                                    .addComponent(lbl_edadCrearUsu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_edadCrearUsu)
                                    .addComponent(combo_tipoCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombreCrearUsu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombreCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreCrearUsu)
                    .addComponent(txt_nombreCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioCrearUsu)
                    .addComponent(txt_usuarioCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraCrearUsu)
                    .addComponent(txt_contraCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edadCrearUsu)
                    .addComponent(txt_edadCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_tipoCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoCrearUsu))
                .addGap(18, 18, 18)
                .addComponent(btn_crearUsuario)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear Usuario", null, jPanel1, "");

        txt_nombreEditUsu.setToolTipText("Usuario");
        txt_nombreEditUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEditUsuActionPerformed(evt);
            }
        });

        lbl_nombreEditUsu.setText("Nombre Completo");

        lbl_usuarioEditUsu.setText("Usuario");

        txt_usuarioEditUsu.setToolTipText("Usuario");

        lbl_contraEditUsu.setText("Contraseña");

        lbl_edadEditUsu.setText("Edad");

        txt_edadEditUsu.setToolTipText("Usuario");

        lbl_tipoEditUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_editUsuario.setText("Editar Usuario");
        btn_editUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editUsuarioActionPerformed(evt);
            }
        });

        lbl_usuarioBuscUsu.setText("Usuario");

        txt_usuarioBuscUsu.setToolTipText("Usuario");

        btn_buscUsuario.setText("Buscar Usuario");
        btn_buscUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lbl_usuarioBuscUsu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_usuarioBuscUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscUsuario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(btn_editUsuario))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbl_contraEditUsu)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_contraEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbl_usuarioEditUsu)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_usuarioEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbl_edadEditUsu)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_edadEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbl_nombreEditUsu)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_nombreEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_tipoEditUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioBuscUsu)
                    .addComponent(txt_usuarioBuscUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreEditUsu)
                    .addComponent(txt_nombreEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioEditUsu)
                    .addComponent(txt_usuarioEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraEditUsu)
                    .addComponent(txt_contraEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edadEditUsu)
                    .addComponent(txt_edadEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipoEditUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editUsuario)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Editar Usuario", jPanel2);

        lbl_usuarioElimUsu.setText("Usuario");

        txt_usuarioElimUsu.setToolTipText("Usuario");

        btn_eliminarUsuario.setText("Eliminar Usuario");
        btn_eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lbl_usuarioElimUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuarioElimUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminarUsuario)
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuarioElimUsu)
                    .addComponent(txt_usuarioElimUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarUsuario)
                .addGap(110, 110, 110))
        );

        jTabbedPane2.addTab("Eliminar Usuario", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Crear Usuario");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_tipoCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoCrearUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipoCrearUsuActionPerformed

    private void btn_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuarioActionPerformed
        
        String nombre = txt_nombreCrearUsu.getText();
        String usuario = txt_usuarioCrearUsu.getText();
        String contra = txt_contraCrearUsu.getText();
        String edad = txt_edadCrearUsu.getText();
        String tipo = combo_tipoCrearUsu.getSelectedItem().toString();
        
        if(usuarios.crearUsuario(nombre, contra, usuario, edad, tipo)){
            txt_nombreCrearUsu.setText("");
            txt_usuarioCrearUsu.setText("");
            txt_contraCrearUsu.setText("");
            txt_edadCrearUsu.setText("");
            JOptionPane.showMessageDialog(rootPane, "Usuario creado satisfactoriamente!"
                        , "Administrador de Usuarios", WIDTH);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario ya existe!"
                        , "Error al Eliminar", WIDTH);
        }
        
    }//GEN-LAST:event_btn_crearUsuarioActionPerformed

    private void txt_nombreCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCrearUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCrearUsuActionPerformed

    private void btn_eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioActionPerformed
        String usuario = txt_usuarioElimUsu.getText();
        if(usuarios.borrarUsuario(usuario)){
            JOptionPane.showMessageDialog(rootPane, "Usuario eliminado satisfactoriamente!"
                        , "Administrador de Usuarios", WIDTH);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario no existe!"
                        , "Error al Eliminar", WIDTH);
        }
        
        
    }//GEN-LAST:event_btn_eliminarUsuarioActionPerformed

    private void txt_nombreEditUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEditUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEditUsuActionPerformed

    private void btn_editUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editUsuarioActionPerformed
        String nombre = txt_nombreEditUsu.getText();
        String usuario = txt_usuarioEditUsu.getText();
        String contra = txt_contraEditUsu.getText();
        String edad = txt_edadEditUsu.getText();
        String u_buscar = txt_usuarioBuscUsu.getText();
        
        if(usuarios.modificarUsuario(u_buscar,nombre, usuario, contra, edad)){
            
            txt_nombreEditUsu.setText("");
            txt_usuarioEditUsu.setText("");
            txt_contraEditUsu.setText("");
            txt_edadEditUsu.setText("");
            txt_usuarioBuscUsu.setText("");
            JOptionPane.showMessageDialog(rootPane, "Usuario modificado satisfactoriamente!"
                        , "Administrador de Usuarios", WIDTH);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario no existe!"
                        , "Error al Modificar", WIDTH);
        }
    }//GEN-LAST:event_btn_editUsuarioActionPerformed

    private void btn_buscUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscUsuarioActionPerformed
        String usuario = txt_usuarioBuscUsu.getText();
        usu = usuarios.buscarUsuario(usuario);
        if(usu != null){
            txt_edadEditUsu.setText(String.valueOf(usu.getEdad()));
            txt_nombreEditUsu.setText(usu.getNombre());
            txt_contraEditUsu.setText(usu.getPassword());
            txt_usuarioEditUsu.setText(usu.getUserName());
            int n = usuarios.getTipo(usu);
            switch (n) {
                case 0:
                    lbl_tipoEditUsu.setText("Usuario de Tipo Administrativo");
                    break;
                case 1:
                    lbl_tipoEditUsu.setText("Usuario de Tipo Contenido");
                    break;
                case 2:
                    lbl_tipoEditUsu.setText("Usuario de Tipo Limitado");
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario no existe!"
                        , "Error al Buscar", WIDTH);
        }
    }//GEN-LAST:event_btn_buscUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        if (args.length>0){
            
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscUsuario;
    private javax.swing.JButton btn_crearUsuario;
    private javax.swing.JButton btn_editUsuario;
    private javax.swing.JButton btn_eliminarUsuario;
    private javax.swing.JComboBox combo_tipoCrearUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_contraCrearUsu;
    private javax.swing.JLabel lbl_contraEditUsu;
    private javax.swing.JLabel lbl_edadCrearUsu;
    private javax.swing.JLabel lbl_edadEditUsu;
    private javax.swing.JLabel lbl_nombreCrearUsu;
    private javax.swing.JLabel lbl_nombreEditUsu;
    private javax.swing.JLabel lbl_tipoCrearUsu;
    private javax.swing.JLabel lbl_tipoEditUsu;
    private javax.swing.JLabel lbl_usuarioBuscUsu;
    private javax.swing.JLabel lbl_usuarioCrearUsu;
    private javax.swing.JLabel lbl_usuarioEditUsu;
    private javax.swing.JLabel lbl_usuarioElimUsu;
    private javax.swing.JTextField txt_contraCrearUsu;
    private javax.swing.JTextField txt_contraEditUsu;
    private javax.swing.JTextField txt_edadCrearUsu;
    private javax.swing.JTextField txt_edadEditUsu;
    private javax.swing.JTextField txt_nombreCrearUsu;
    private javax.swing.JTextField txt_nombreEditUsu;
    private javax.swing.JTextField txt_usuarioBuscUsu;
    private javax.swing.JTextField txt_usuarioCrearUsu;
    private javax.swing.JTextField txt_usuarioEditUsu;
    private javax.swing.JTextField txt_usuarioElimUsu;
    // End of variables declaration//GEN-END:variables
}
