/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicketJavaGUI;

/**
 *
 * @author DReyes
 */
public class JavaTicket extends javax.swing.JFrame {

    IngresoUsuarios ingreso_usu;
    AdministradorUsuarios au = new AdministradorUsuarios();
    AdministradorEventos ae = new AdministradorEventos();
    String usu;
    int tipo;

    public void setUsu(String usu) {
        this.usu = usu;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    
    public JavaTicket() {
        
        initComponents();
    }
    
    private void verificarAcceso(int t,String u){
        switch (t) {
            case 0:
                menu_menuPrincipal.setEnabled(true);
                imenu_cerrSesion.setEnabled(true);
                ismenu_crearEditElimEvento.setEnabled(true);
                smenu_adminEventos.setEnabled(true);
                imenu_adminUsuarios.setEnabled(true);
                imenu_reportes.setEnabled(true);
                imenu_iniSesion.setEnabled(false);
                lbl_saludo2.setText("Bienvenido "+u+"!");
                break;
            case 1:
                menu_menuPrincipal.setEnabled(true);
                imenu_cerrSesion.setEnabled(true);
                ismenu_crearEditElimEvento.setEnabled(true);
                imenu_adminUsuarios.setEnabled(false);
                imenu_reportes.setEnabled(true);
                imenu_iniSesion.setEnabled(false);
                lbl_saludo2.setText("Bienvenido "+u+"!");
                break;
            case 2:
                menu_menuPrincipal.setEnabled(true);
                imenu_cerrSesion.setEnabled(true);
                ismenu_crearEditElimEvento.setEnabled(false);
                imenu_adminUsuarios.setEnabled(false);
                imenu_reportes.setEnabled(true);
                imenu_iniSesion.setEnabled(false);
                lbl_saludo2.setText("Bienvenido "+u+"!");
                break;
            default:
                menu_menuPrincipal.setEnabled(false);
                imenu_cerrSesion.setEnabled(false);
                imenu_iniSesion.setEnabled(true);
                lbl_saludo2.setText("Bienvenido! Inicie Sesión para Continuar.");
                break;
        }
    }
    
    public JavaTicket(String u, int t) {
        usu = u;
        tipo = t;
        initComponents();
        verificarAcceso(-1,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_saludo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_menuPrincipal = new javax.swing.JMenu();
        smenu_adminEventos = new javax.swing.JMenu();
        ismenu_crearEditElimEvento = new javax.swing.JMenuItem();
        ismenu_verEvento = new javax.swing.JMenuItem();
        imenu_adminUsuarios = new javax.swing.JMenuItem();
        imenu_reportes = new javax.swing.JMenuItem();
        menu_menuSesion = new javax.swing.JMenu();
        imenu_iniSesion = new javax.swing.JMenuItem();
        imenu_cerrSesion = new javax.swing.JMenuItem();
        menu_acercaDe = new javax.swing.JMenu();
        imenu_proyecto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_saludo2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_saludo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_menuPrincipal.setText("Menú");

        smenu_adminEventos.setText("Administración de Eventos");

        ismenu_crearEditElimEvento.setText("Crear/Editar/Eliminar Evento");
        ismenu_crearEditElimEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ismenu_crearEditElimEventoActionPerformed(evt);
            }
        });
        smenu_adminEventos.add(ismenu_crearEditElimEvento);

        ismenu_verEvento.setText("Ver Evento");
        smenu_adminEventos.add(ismenu_verEvento);

        menu_menuPrincipal.add(smenu_adminEventos);

        imenu_adminUsuarios.setText("Administración de Usuarios");
        imenu_adminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_adminUsuariosActionPerformed(evt);
            }
        });
        menu_menuPrincipal.add(imenu_adminUsuarios);

        imenu_reportes.setText("Reportes");
        menu_menuPrincipal.add(imenu_reportes);

        jMenuBar1.add(menu_menuPrincipal);

        menu_menuSesion.setText("Sesión");

        imenu_iniSesion.setText("Iniciar Sesión");
        imenu_iniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_iniSesionActionPerformed(evt);
            }
        });
        menu_menuSesion.add(imenu_iniSesion);

        imenu_cerrSesion.setText("Cerrar Sesión");
        imenu_cerrSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_cerrSesionActionPerformed(evt);
            }
        });
        menu_menuSesion.add(imenu_cerrSesion);

        jMenuBar1.add(menu_menuSesion);

        menu_acercaDe.setText("Acerca de...");

        imenu_proyecto.setText("Proyecto");
        imenu_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_proyectoActionPerformed(evt);
            }
        });
        menu_acercaDe.add(imenu_proyecto);

        jMenuBar1.add(menu_acercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_saludo2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_saludo2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imenu_adminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_adminUsuariosActionPerformed
       
        au.setVisible(true);
    }//GEN-LAST:event_imenu_adminUsuariosActionPerformed

    private void imenu_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_proyectoActionPerformed
        
    }//GEN-LAST:event_imenu_proyectoActionPerformed

    private void imenu_iniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_iniSesionActionPerformed
        ingreso_usu = new IngresoUsuarios(au.usuarios);
        ingreso_usu.setVisible(true);
        
        ingreso_usu.setNewInterface(new NewInterface() {

            @Override
            public void UsuarioIngresando(String usu, int tipo) {
                verificarAcceso(tipo,usu);
                System.out.println("Ingreso!");
            }
        
        });
        //String n_usu = au.iu.user.getNombre();
        //lbl_saludo2.setText("Bienvenido "+n_usu+"!");
    }//GEN-LAST:event_imenu_iniSesionActionPerformed

    private void imenu_cerrSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_cerrSesionActionPerformed
        
        verificarAcceso(-1,"");
    }//GEN-LAST:event_imenu_cerrSesionActionPerformed

    private void ismenu_crearEditElimEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ismenu_crearEditElimEventoActionPerformed
        ae.setVisible(true);
    }//GEN-LAST:event_ismenu_crearEditElimEventoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JavaTicket jt = new JavaTicket("",-1);
                        jt.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imenu_adminUsuarios;
    private javax.swing.JMenuItem imenu_cerrSesion;
    private javax.swing.JMenuItem imenu_iniSesion;
    private javax.swing.JMenuItem imenu_proyecto;
    private javax.swing.JMenuItem imenu_reportes;
    private javax.swing.JMenuItem ismenu_crearEditElimEvento;
    private javax.swing.JMenuItem ismenu_verEvento;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel lbl_saludo2;
    private javax.swing.JMenu menu_acercaDe;
    private javax.swing.JMenu menu_menuPrincipal;
    private javax.swing.JMenu menu_menuSesion;
    private javax.swing.JMenu smenu_adminEventos;
    // End of variables declaration//GEN-END:variables
}
