/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicketJavaGUI;

/**
 *
 * @author DReyes
 */
public class JavaTicket extends javax.swing.JFrame {

    /**
     * Creates new form JavaTicket 
     */
    
    public JavaTicket() {
        initComponents();
    }
    
    
    public JavaTicket(String usu, int tipo) {
        String usuario = usu;
        initComponents();
        lbl_saludo2.setText("Bienvenido "+usu+"!");
        switch (tipo) {
            case 1:
                menu_adminUsuarios.setEnabled(false);
                break;
            case 2:
                imenu_crearEvento.setEnabled(false);
                imenu_eliminarEvento.setEnabled(false);
                imenu_editarEvento.setEnabled(false);
                break;
            case 3:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_saludo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_adminEventos = new javax.swing.JMenu();
        imenu_crearEvento = new javax.swing.JMenuItem();
        imenu_eliminarEvento = new javax.swing.JMenuItem();
        imenu_editarEvento = new javax.swing.JMenuItem();
        imenu_verEvento = new javax.swing.JMenuItem();
        menu_adminUsuarios = new javax.swing.JMenu();
        menu_reportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_saludo2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_saludo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_adminEventos.setText("Adminitración de Eventos");

        imenu_crearEvento.setText("Crear un Evento");
        imenu_crearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_crearEventoActionPerformed(evt);
            }
        });
        menu_adminEventos.add(imenu_crearEvento);

        imenu_eliminarEvento.setText("Eliminar un Evento");
        imenu_eliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imenu_eliminarEventoActionPerformed(evt);
            }
        });
        menu_adminEventos.add(imenu_eliminarEvento);

        imenu_editarEvento.setText("Editar un Evento");
        menu_adminEventos.add(imenu_editarEvento);

        imenu_verEvento.setText("Ver Evento");
        menu_adminEventos.add(imenu_verEvento);

        jMenuBar1.add(menu_adminEventos);

        menu_adminUsuarios.setText("Administración de Usuarios");
        jMenuBar1.add(menu_adminUsuarios);

        menu_reportes.setText("Reportes");
        jMenuBar1.add(menu_reportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_saludo2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_saludo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imenu_crearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_crearEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imenu_crearEventoActionPerformed

    private void imenu_eliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imenu_eliminarEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imenu_eliminarEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaTicket().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imenu_crearEvento;
    private javax.swing.JMenuItem imenu_editarEvento;
    private javax.swing.JMenuItem imenu_eliminarEvento;
    private javax.swing.JMenuItem imenu_verEvento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_saludo2;
    private javax.swing.JMenu menu_adminEventos;
    private javax.swing.JMenu menu_adminUsuarios;
    private javax.swing.JMenu menu_reportes;
    // End of variables declaration//GEN-END:variables
}
